### ISSUE TITLE
Move website to new repo

### ISSUE THREAD

**Issue by MichielBijl** [role-drinks/role-drinks.de#6]
Can we move this into a new repo? I want to transfer the roledrinks.nl repo here, but since this is a fork of that; I can't. Creating a new repo and moving the files there should do it.

**Comment by lassediercks** [comment]
yeah, can you give admin rights to the repo?

**Comment by MichielBijl** [comment]
What do you mean? Are you able to create a new repository in the organisation?

**Comment by lassediercks** [comment]
ah you're right. I pushed the repo to https://github.com/role-drinks/roledrinks.de so you can delete this one

**Comment by MichielBijl** [comment]
Cool! Thank you.
